name: Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: lein deps
      - name: Start mongo
        run: sudo docker run --rm -d -e POSTGRES_DB=overlook -p 5432:5432 postgres
      - name: Run tests
        run: lein test
